<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPaqlxck\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPaqlxck/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPaqlxck.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPaqlxck\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPaqlxck\appDevDebugProjectContainer([
    'container.build_hash' => 'Paqlxck',
    'container.build_id' => '0e2d41a9',
    'container.build_time' => 1553610559,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPaqlxck');
