<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVuutqsv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVuutqsv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVuutqsv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVuutqsv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVuutqsv\appDevDebugProjectContainer([
    'container.build_hash' => 'Vuutqsv',
    'container.build_id' => '1b08086a',
    'container.build_time' => 1553874882,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVuutqsv');
